improved build deployment utility and fixed some minor issues

diff --git a/build b/build
--- a/build
+++ b/build
@@ -31,30 +31,34 @@ flavors="TTGO_T7 TTGO_TDISPLAY ESP32DEVKIT M5PICOD4 HELTEC WEMOSOLED TTGO_TQ M5A
 flavors_ci="TTGO_TDISPLAY ESP32C3LOLIN ESP32S2LOLIN TTGO_T7S3 XIAO_C6"
 
 showHelp () {
-  echo ""
+  echo
   echo "************************************************"
   echo "** Build release flavor or installer package **"
   echo "************************************************"
-  echo ""
-  echo "Usage: ./build [flavor|list|all|installer|github|ota|webi|help|print|list|clean]"
-  echo ""
+  echo
+  echo "Usage: ./build [flavor|wokwi|all|list|installer|github|ota|webi|ci|help|print|list|clean]"
+  echo
   echo "example: ./build clean"
   echo "example: ./build all"
   echo -n "example: ./build "; echo ${flavors} | awk '{print $1}'
   echo "example: ./build installer"
-  echo ""
+  echo
   echo "Supported boards: "
   echo "./build list"
-  echo ""
+  echo
+  echo "Small CI test:"
+  echo "./build ci"
+  echo
   echo "Build installer option will build a installer package for Linux"
   echo "with OTA support and USB support"
-  echo ""
+  echo
 }
 
 clean () {
   echo "Clean installer directory.."
   rm -rf $RELDIR/$BINDIR
   rm -rf $RELDIR/$MANIFEST
+  rm -rf $RELDIR/wokwi
   rm -f $INSDIR/*.bin
   rm -f $INSDIR/*.py  
   for flavor in $flavors; do
@@ -62,14 +66,17 @@ clean () {
     pio run -s -e $flavor -t clean
     rm -f "sdkconfig.$flavor"
   done
+  # we need repeat this because clean generate it
+  echo "Clean Manifests.."
+  rm -rf $RELDIR/$MANIFEST
 }
 
 build () {
-  echo ""
+  echo
   echo "***********************************************"
   echo "** Building $1"
   echo "***********************************************"
-  echo ""
+  echo
 
   pio run -s -e $1
   if [ $? -ne 0 ]; then
@@ -77,24 +84,28 @@ build () {
     exit 1
   fi
 
-  echo ""
+  echo
   echo "***********************************************"
   echo "** Firmware $1 output:"
+  echo "***********************************************"
   FIRMDIR=$RELDIR/$BINDIR/$1
   mkdir -p $FIRMDIR 
   cp $OUTDIR/$1/firmware.bin $FIRMDIR/${NAME}_${1}_rev${SRC_REV}.bin
   if [ $1 == ESP32C3 ] || [ $1 == ESP32C3LOLIN ] || [ $1 == ESP32C3SEEDX ] || [ $1 == ESP32C3OIPLUS ]; then
     python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32c3 merge_bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 80m --flash_size 4MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
-  elif [ $1 == ESP32S3 ] || [ $1 == TTGO_T7S3 ]; then
+  elif [ $1 == ESP32S3 ] || [ $1 == TTGO_T7S3 ] || [ $1 == XIAO_S3 ]; then
     python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32s3 merge_bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 80m --flash_size 8MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
+  elif [ $1 == ESP32S2LOLIN ]; then
+    python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32s2 merge_bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 80m --flash_size 8MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
+  elif [ $1 == XIAO_C6 ]; then
+    python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool --chip esp32c6 merge-bin -o  $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash-mode dio --flash-freq 80m --flash-size 8MB 0x0000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
   else
     python3 ${PIO_HOME}/packages/tool-esptoolpy/esptool.py --chip esp32 merge_bin -o $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin --flash_mode dio --flash_freq 40m --flash_size 4MB 0x1000 $OUTDIR/$1/bootloader.bin 0x8000 $OUTDIR/$1/partitions.bin 0xe000 ${PIO_HOME}/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $OUTDIR/$1/firmware.bin
   fi
-  echo "** MD5:"
+  echo "MD5:"
   md5sum $FIRMDIR/${NAME}_${1}_rev${SRC_REV}_merged.bin
   md5sum $FIRMDIR/${NAME}_${1}_rev${SRC_REV}.bin
   echo "***********************************************"
-  echo ""
 }
 
 wokwi_setup () {
@@ -108,12 +119,13 @@ wokwi_setup () {
 }
 
 buildInstaller () {
+  check_firmware_dir
   echo "***********************************************"
   echo "** Building installer with target: $TARGET"
   echo "***********************************************"
-  echo ""
+  echo
   echo "Update installer tool.."
-  cp $PIO_HOME/packages/tool-esptoolpy@1.30300.0/esptool.py $INSDIR/
+  cp ${PIO_HOME}/packages/tool-esptoolpy/esptool.py $INSDIR/
   echo "Update installer flavors.."
   rm -f $INSDIR/*.bin
   cp $RELDIR/$BINDIR/*/*${SRC_REV}_merged.bin $INSDIR/
@@ -122,12 +134,53 @@ buildInstaller () {
   cd $INSDIR/..
   rm -f ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
   zip -r ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip ${NAME}_installer
-  echo ""
+  echo
   du -hs ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
-  echo ""
+  echo
+}
+
+print_publish_summary () {
+  echo 
+  echo "****************************"
+  echo "** ! ! W A R N I N G ! ! **"
+  echo "***************************"
+  echo 
+  echo "Publish release:"
+  echo 
+  echo "${NAME}_${SRC_VER}_rev${SRC_REV}"
+  echo "TARGET: ${TARGET}"
+  echo
+}
+
+check_firmware_dir () {
+  FIRMDIR=$RELDIR/$BINDIR
+  if [ ! -d "$FIRMDIR" ]; then
+    echo "ERROR: Please first build any flavor!"
+    exit 1
+  fi
+}
+
+check_installer () {
+  if [ ! -e ${RELDIR}/installer/${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip ]; then
+    echo "ERROR: Please run first: 'build installer'"
+    exit 1
+  fi
+}
+
+check_confirmation () {
+  read -p "Are you sure? " -n 1 -r
+  echo
+  if [[ ! $REPLY =~ ^[Yy]$ ]]
+  then
+    exit 1
+  fi
+  echo
 }
 
 publish_release () {
+  check_installer 
+  print_publish_summary  
+  check_confirmation
   cd $INSDIR/..
   # github-release upload --owner ${OWNER} --repo ${REPO} --tag "rev${SRC_REV}" --release-name "rev${SRC_REV} v${SRC_VER}" --body "${COMMIT_LOG}" ${NAME}_${TARGET}_rev${SRC_REV}_${DATE}.zip
   echo "Publishing release: v${SRC_VER} rev${SRC_REV}" 
@@ -138,25 +191,40 @@ publish_release () {
 }
 
 publish_release_ota () {
+  check_installer 
+  print_publish_summary  
+  check_confirmation 
   scp $RELDIR/$BINDIR/*/*${SRC_REV}.bin canairio:$canairio_target/$TARGET
   scp $RELDIR/$MANIFEST/$TARGET/*.json canairio:$canairio_target/$TARGET
 }
 
 publish_release_webtools () {
+  check_installer 
+  print_publish_summary  
+  check_confirmation 
   scp $INSDIR/*.bin canairio:$canairio_target/webi/$TARGET 
   scp $INSDIR/*.txt canairio:$canairio_target/webi/$TARGET 
   scp $INSDIR/*.md canairio:$canairio_target/webi/$TARGET 
   scp $RELDIR/$MANIFEST/webi/$TARGET/*.json canairio:$canairio_target/webi/$TARGET
 }
+print_time () {
+  echo
+  secs=$SECONDS
+  printf 'TOTAL TIME: %02dh:%02dm:%02ds\r\n' $((secs/3600)) $((secs%3600/60)) $((secs%60))
+  echo
+}
+
+mark=0
+
+print_time_mark () {
+  secs=$((SECONDS - mark))
+  printf 'LAST BUILD: %02dh:%02dm:%02ds\r\n' $((secs/3600)) $((secs%3600/60)) $((secs%60))
+  mark=$SECONDS
+}
 
 printOutput () {
-  echo ""
-  FIRMDIR=$RELDIR/$BINDIR
-  if [ ! -d "$FIRMDIR" ]; then
-    echo "Please first build any flavor!"
-    echo ""
-    exit 1
-  fi
+  echo
+  check_firmware_dir 
   mkdir -p $INSDIR
   rm -f $INSDIR/md5output.txt
   touch $INSDIR/md5output.txt
@@ -167,7 +235,7 @@ printOutput () {
   done
   cat ../../$INSDIR/md5output.txt
   cd ../..
-  echo "" 
+  print_time
 }
 
 
@@ -196,19 +264,24 @@ else
       ;;
 
     print)
+      SECONDS=0 
       printOutput
       ;;
 
     all)
+      SECONDS=0 
       for flavor in $flavors; do
           build $flavor
+          print_time_mark
       done     
       printOutput
       ;;
 
     ci)
+      SECONDS=0 
       for flavor in $flavors_ci; do
           build $flavor
+          print_time_mark
       done     
       printOutput
       ;;
@@ -238,13 +311,15 @@ else
 
     *)
       if [[ $flavors == *"$1"* ]]; then
+        SECONDS=0 
         build $1
+        print_time
       else
-        echo ""
+        echo
         echo "ERROR: Flavor not found!"
-        echo ""
+        echo
         echo "Please check flavor parameter with 'list' command"
-        echo ""
+        echo
         exit 1
       fi
       ;;
